### ISSUE TITLE
Add timecode to output SDI

### ISSUE THREAD

**Issue by tetsutaroh** [RenderHeads/UnityPlugin-AVProDeckLink#38] opened 2021-01-18 04:48 UTC
Is it possible to add timecode to the output?
I wish I could add the SDI input timecode to the output timecode.
In a similar discussion in the past, it was said that it would be supported in the future.
I would like to know if it is currently in progress.

**Comment by AndrewRH** [comment] 2021-01-25 12:39
We're looking into this now and will hopefully have more information by the end of the week

**Comment by RenderHeadsMrT** [comment] 2021-02-02 14:50
Duplicate of #3

**Closed by RenderHeadsMrT** 2021-02-02 14:50 UTC
Labels: enhancement
